ANDROID_VERSION := 15
AURORAVERSION := 2.0-beta

AURORA_BUILD_TYPE ?= UNOFFICIAL
AURORA_MAINTAINER ?= UNKNOWN
AURORA_DATE_YEAR := $(shell date -u +%Y)
AURORA_DATE_MONTH := $(shell date -u +%m)
AURORA_DATE_DAY := $(shell date -u +%d)
AURORA_DATE_HOUR := $(shell date -u +%H)
AURORA_DATE_MINUTE := $(shell date -u +%M)
AURORA_BUILD_DATE := $(AURORA_DATE_YEAR)$(AURORA_DATE_MONTH)$(AURORA_DATE_DAY)-$(AURORA_DATE_HOUR)$(AURORA_DATE_MINUTE)
TARGET_PRODUCT_SHORT := $(subst aurora_,,$(AURORA_BUILD))

# OFFICIAL_DEVICES
ifeq ($(AURORA_BUILD_TYPE), OFFICIAL)
  LIST = $(shell cat vendor/aurora/config/aurora.devices)
    ifeq ($(filter $(AURORA_BUILD), $(LIST)), $(AURORA_BUILD))
      IS_OFFICIAL=true
      AURORA_BUILD_TYPE := OFFICIAL
    endif
    ifneq ($(IS_OFFICIAL), true)
      AURORA_BUILD_TYPE := UNOFFICIAL
      $(error Device is not official "$(AURORA_BUILD)")
    endif
endif

AURORA_VERSION := $(AURORAVERSION)-$(AURORA_BUILD)-$(AURORA_BUILD_DATE)-VANILLA-$(AURORA_BUILD_TYPE)
ifeq ($(WITH_GMS), true)
AURORA_VERSION := $(AURORAVERSION)-$(AURORA_BUILD)-$(AURORA_BUILD_DATE)-GAPPS-$(AURORA_BUILD_TYPE)
endif
AURORA_MOD_VERSION :=$(ANDROID_VERSION)-$(AURORAVERSION)
AURORA_DISPLAY_VERSION := AuroraDroid-$(AURORAVERSION)-$(AURORA_BUILD_TYPE)
AURORA_DISPLAY_BUILDTYPE := $(AURORA_BUILD_TYPE)
AURORA_FINGERPRINT := AuroraDroid/$(AURORA_MOD_VERSION)/$(TARGET_PRODUCT_SHORT)/$(AURORA_BUILD_DATE)

# AURORA System Version
PRODUCT_SYSTEM_DEFAULT_PROPERTIES += \
  ro.aurora.version=$(AURORA_DISPLAY_VERSION) \
  ro.aurora.build.status=$(AURORA_BUILD_TYPE) \
  ro.modversion=$(AURORA_MOD_VERSION) \
  ro.aurora.build.date=$(AURORA_BUILD_DATE) \
  ro.aurora.buildtype=$(AURORA_BUILD_TYPE) \
  ro.aurora.fingerprint=$(AURORA_FINGERPRINT) \
  org.aurora.version=$(AURORAVERSION) \
  ro.aurora.maintainer=$(AURORA_MAINTAINER)
